### ISSUE TITLE
Separated buttons height / width showing double

### ISSUE THREAD

**Issue by ScumbagSteve** [inventwo/ioBroker.vis-2-widgets-inventwo#10]
When using 

type = Switch 
with
mode = separated buttons

the button widths can be adjusted, but the height can not.
I assume the second "button width" was meant to be "button height" - as it also doesn't seem to have any function.

<img width="1185" alt="image" src="https://github.com/inventwo/ioBroker.vis-2-widgets-inventwo/assets/8447146/8d21b1d5-f462-4689-b81f-dff6e8cc588f">

v0.1.2

**Comment by jkvarel** [comment]
The second button width is not in use and will be removed in the next update. To change the height  just change the widget height like with the single widgets.

**Comment by jkvarel** [comment]
Fixed in version 0.1.3
