### ISSUE TITLE
Escape Popup / Button color

### ISSUE THREAD

**Issue by ScumbagSteve** [inventwo/ioBroker.vis-2-widgets-inventwo#11]
With the VIS1 widgets for "view in dialog it was possible to customize the "x" button color:
<img width="435" alt="image" src="https://github.com/inventwo/ioBroker.vis-2-widgets-inventwo/assets/8447146/10d11416-55f3-406c-851b-f7928816e873">

Also the dialog closed when clicking in the background, which usability-wise is the far superior option to me, compared to clicking the small button.

Both functions would be highly appreciated :)
v0.1.2

**Comment by jkvarel** [comment]
Both functions will come in a future version

**Comment by ScumbagSteve** [comment]
Any plans when this will be implemented? Clicking the small button is truly a pain right now. 😄

**Comment by jkvarel** [comment]
Both functions and a few options more added in v0.1.7
