### ISSUE TITLE
Entering a quotation mark in the value field crashes the editor

### ISSUE THREAD

**Issue by Horgul123** [inventwo/ioBroker.vis-2-widgets-inventwo#12]
When you enter a quotation mark at the beginning in the value field of a state, the editor crashes. 
(Tested with V0.1.2)

![Screenshot 2024-04-12 071431](https://github.com/inventwo/ioBroker.vis-2-widgets-inventwo/assets/45976162/2a73b4ef-9581-4e06-b4ed-97492021196c)

**Comment by jkvarel** [comment]
Fixed in version 0.1.3
