### ISSUE TITLE
Aspect Ratio 'Image'

### ISSUE THREAD

**Issue by StoniHome** [inventwo/ioBroker.vis-2-widgets-inventwo#15]
v0.1.5

I have found that it doesn't matter whether I select Icon or Image under 'Content' in the universal widget, the image is always displayed with the same aspect ratio.

This means that if I have a roughly rectangular image (whether horizontal or vertical), it will then be compressed so that it looks square.

See attached Images
![tablet_full](https://github.com/inventwo/ioBroker.vis-2-widgets-inventwo/assets/101056396/d8b6d724-6caa-4ad9-9832-cc91ea1c403a)

![tablet](https://github.com/inventwo/ioBroker.vis-2-widgets-inventwo/assets/101056396/d6c5c720-cf2c-4fc3-9f12-c177672b539e)

**Comment by jkvarel** [comment]
Fixed with v0.1.7
