### ISSUE TITLE
Universal Widget - Seperated Buttons Background Color ändert sich nicht

### ISSUE THREAD

**Issue by StoniHome** [inventwo/ioBroker.vis-2-widgets-inventwo#18]
v0.1.5

Ich hab ein Universal Widget mit drei Buttons erstellt, welches zwischen den verschiedenen Alarm-States umschalten soll.
Dies funktioniert auch soweit, also die States werden geschaltet, allerdings verändert sich die Farbe der Button nicht.

Hier das Widget

![alarm1](https://github.com/inventwo/ioBroker.vis-2-widgets-inventwo/assets/101056396/256c4eee-f721-4a4e-8442-6601cade3520)

und hier die Einstellungen für die States [1] bis [3]

![alarm2](https://github.com/inventwo/ioBroker.vis-2-widgets-inventwo/assets/101056396/849b2df2-9f3d-4563-a805-694842445840)

wenn jetzt der State [1] (oder [2] oder [3] Value = 0 true ist, dann bleibt die 'Background color' grün, sollte aber eigentlich rot werden.

siehe auch forum [iobroker forum](https://forum.iobroker.net/topic/73883/test-vis-2-inventwo-widgets/78?_=1714994100458)

**Comment by jkvarel** [comment]
Hab den Fehler gefunden. Am Wochenende kommt ein Update. Mit dem ist es dann behoben.

**Comment by jkvarel** [comment]
Mit Version 0.1.7 behoben
