### ISSUE TITLE
Colored icons / images

### ISSUE THREAD

**Issue by backfisch88** [inventwo/ioBroker.vis-2-widgets-inventwo#19]
Hello

I have used the Universal Widget to create buttons that look like this in VIS (see pictures)
Unfortunately it is not possible to color the icons in the Universal Widget in VIS 2. (I have set the image color #000000 in VIS1). Unfortunately this option is not available in VIS2 Widget. 
![IMG_8023](https://github.com/inventwo/ioBroker.vis-2-widgets-inventwo/assets/7542512/a2185ba7-0ad6-4002-9f4f-4af2d8cd6989)
![IMG_8024](https://github.com/inventwo/ioBroker.vis-2-widgets-inventwo/assets/7542512/28f44cc3-b543-484f-8d4e-457887b1e1f7)
![IMG_8026](https://github.com/inventwo/ioBroker.vis-2-widgets-inventwo/assets/7542512/094c2cad-640c-4e8a-9a28-e7d233ffb887)

**Comment by jkvarel** [comment]
Setting the color currently only works for images in SVG format. Support for png and jpg will come in the future.

**Comment by backfisch88** [comment]
Thanks!
