### ISSUE TITLE
Compare by widget default - Funktioniert nicht

### ISSUE THREAD

**Issue by Nokz85** [inventwo/ioBroker.vis-2-widgets-inventwo#24]
Version 0.1.9

Ich habe einen universal Button angelegt, welcher eine View öffnen soll (das funktioniert auch wunderbar).
Je nach Zustand der ObjectID soll ein anderes Icon angezeigt werden. Sofern ich in dem jeweilige State die betroffene ObjectID zum vergleich angebe funktioniert es wunderbar. Stelle ich allerdings die Auswertung auf "Compare by widget default", dann wird nur noch der default state angezeigt und egal welcher Wert in der ObjectID vorliegt, es passieren keine Änderungen mehr.

![image](https://github.com/inventwo/ioBroker.vis-2-widgets-inventwo/assets/169972383/ae6c5e2a-9c3c-4854-9e80-eed9be01caaa)

State ohne erneute angabe der ObjectID von den Einstellungen unter "Allgemein"
![image](https://github.com/inventwo/ioBroker.vis-2-widgets-inventwo/assets/169972383/a46a315e-7253-4da8-bc2b-01f100d58583)

Ergebnis:
![image](https://github.com/inventwo/ioBroker.vis-2-widgets-inventwo/assets/169972383/d3e5d86e-ad36-41aa-8e3c-b3d512e3a309)

Stelle ich im State die Auswertung auf Value und gebe erneut die gleiche ObjectID an, so funktioniert es:
![image](https://github.com/inventwo/ioBroker.vis-2-widgets-inventwo/assets/169972383/a5251fda-d5ff-4af1-8943-043dc240eb36)
![image](https://github.com/inventwo/ioBroker.vis-2-widgets-inventwo/assets/169972383/78e30f01-be42-4207-897a-b1e7ba68a5a8)

Im Tooltip steht ja, dass sofern hier keine Angabe gemacht wird, die ObjectID von oben genutzt werden soll:
![image](https://github.com/inventwo/ioBroker.vis-2-widgets-inventwo/assets/169972383/99f8acb2-5b7b-4e0d-a0f1-8eab6c747392)
Die Umstellung auf Value und "ObjectID = leer" funktioniert auch nicht.

**Comment by Nokz85** [comment]
Ich habe gerade einen Button als normalen Switch angelegt und hier funktioniert das "Compare by widget" ohne Probleme bisher.
Das Problem wird also wohl beim Type "View in dialog" liegen.
Das hier funktioniert:
![image](https://github.com/inventwo/ioBroker.vis-2-widgets-inventwo/assets/169972383/ed5cfe59-15cc-434a-98e2-f0cde997300f)
![image](https://github.com/inventwo/ioBroker.vis-2-widgets-inventwo/assets/169972383/a258ca43-de36-47d3-9f52-9a15b65ccf8e)
![image](https://github.com/inventwo/ioBroker.vis-2-widgets-inventwo/assets/169972383/8e69a77e-162d-46f7-83ea-110fbffefc9d)
![image](https://github.com/inventwo/ioBroker.vis-2-widgets-inventwo/assets/169972383/8c7e6e58-58ec-4544-9265-cf3e0d3430d9)
![image](https://github.com/inventwo/ioBroker.vis-2-widgets-inventwo/assets/169972383/a59ec9f5-8ef6-48c2-b130-06091e76fa52)

**Comment by jkvarel** [comment]
Mit v.0.1.10 behoben
