### ISSUE TITLE
Slider Widget doesn't change Text-Color (No Step-Numbers on dark Background)

### ISSUE THREAD

**Issue by StoniHome** [inventwo/ioBroker.vis-2-widgets-inventwo#25]
v0.1.9

Slider Widget doesn't show Steps-Numbers on dark Background because the Text-Color default is 'black'. If I want to change the Text-Color with 'CSS-Schriftart&Text' nothing happen. It doesn't matter what color i choose.

If I turn the Widgets Background Color to 'White' (#ffffff) than i see the Step-Numbers in Black.

**Comment by jkvarel** [comment]
Fixed in v0.1.10. Font and text settings are now applied to the slider
