### ISSUE TITLE
Bindings do not load correctly

### ISSUE THREAD

**Issue by ScumbagSteve** [inventwo/ioBroker.vis-2-widgets-inventwo#9]
I use bindings in the field "Beschriftung".
The bindings loads a text saved in a datapoint --> {0_userdata.0.TextDatapoint}

I noticed the bindings only loads, as soon as I click the widget. In the editor and when opening the view, the binding shows null:

<img width="480" alt="image" src="https://github.com/inventwo/ioBroker.vis-2-widgets-inventwo/assets/8447146/dcca6952-af0d-4d9e-824b-e7411ce2d21b">

**Comment by jkvarel** [comment]
Which adapter version is installed?

**Comment by ScumbagSteve** [comment]
The current git version as of 3 days ago (I think no more updates since then).

**Comment by Horgul123** [comment]
@ScumbagSteve Yesterday a new version was released which fixes some bugs.

**Comment by ScumbagSteve** [comment]
@Horgul123 I am somehow no longer able to update the adapter. I even tried uninstalling, but now I am stuck with not being able to install again. No error message whatsoever, the window just closes without installing.
Is there an issue with the current release? Never had this behavior

**Comment by Horgul123** [comment]
@ScumbagSteve How do you try to install?
Maybe try 
iob url iobroker.vis-2-widgets-inventwo@latest
from the command line
Works fine for me
Didn't know the "iob url" command before I had issues installing this adapter. Someone gave me this hint

**Comment by ScumbagSteve** [comment]
@Horgul123 thanks, that worked. Before I tried installing via "expert mode" and by clicking the GitHub Button and pasting the URL. Weird that this doesn't work with this version.
Unfortunately the new version did not resolve the "null" issue.

**Comment by ScumbagSteve** [comment]
I think I can provide more details to the issue.
The widgets where I have the issues are set up as "text-widget". That means there is no "Object ID" entered.
In the end it's just the widget with a binding in fields "value true" and "value false", so that I get shown the content of the binding in a nice styled widget. Pressing the widget should not do anything, as I have no Object ID provided.

Considering the changelog I assume it has to do with the comparators. The widget doesn't have a ObjectID to apply the comparator on and maybe this way the result is corrupt.

When I click the widget, it writes a value to the (non existing) ObjectID and this way it then has a value to compare with - resulting in "null" being changed to the binding from "value true" or "value false".

**Comment by Horgul123** [comment]
@ScumbagSteve jkvarel mentioned somewhere that installing via Github is not working and npm should be used as long as it's not available in the repository

**Comment by Horgul123** [comment]
@ScumbagSteve Value true/false? Where could I find these fields? I have default state additional states. Could you please post a screenshot?

**Comment by ScumbagSteve** [comment]
Sure thing :)

<img width="1440" alt="image" src="https://github.com/inventwo/ioBroker.vis-2-widgets-inventwo/assets/8447146/ad668913-dbfd-4c7e-8402-2fff84a281d7">

**Comment by Horgul123** [comment]
Hmmm... I think you're using the old inventwo-widgets.... The new one look like this...

![Screenshot 2024-04-09 105504](https://github.com/inventwo/ioBroker.vis-2-widgets-inventwo/assets/45976162/debd52ef-743f-41c9-8a7d-a35955100f92)

You find them in this block in the editor

![Screenshot 2024-04-09 105656](https://github.com/inventwo/ioBroker.vis-2-widgets-inventwo/assets/45976162/09729501-41ff-460d-b9cb-10508e9cacad)


Please double-check if you're really using the new widgets :)

**Comment by jkvarel** [comment]
Yes thats the old widget. They are not completely working in VIS 2 and never will.
